#undef TAPPING_TERM
#define TAPPING_TERM 250
// Better rolling keys
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "qGNl4/bvlGjj"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

